### PR TITLE
Update DevFaqCustomDebugger.adoc

### PR DESCRIPTION
**Pull request by vieiro**
Let's add a link to the web.archive for this interesting article at DZone.

### CODE REVIEW

**Review by mbien — APPROVED** [review]
sad that dzone took down all those articles.

**Comment by vieiro** [comment]
Thanks @mbien ! Merging...

**Comment by ebarboni** [comment]
+1 could we rewrite it with quote to original authors ?

**Comment by vieiro** [comment]
@ebarboni I don't understand "quote to original authors', once one visits the page you can see the original authors there, right? Isn't this enough?

**Comment by ebarboni** [comment]
Sorry I was thinking on writting the content in adoc with the authors name exposed + source to have the content on our repo. Maybe not only for this particular page

**Comment by vieiro** [comment]
@ebarboni Ah, I see.  That's a good idea.

I'm thinking of rebuilding the support for "gdb" in "cnd" so that it can be used elsewhere. For instance for debugging Rust projects. I may want to create new tutorials for this once I'm done. Then we can update this wiki entry to point to the new tutorial.

**Comment by ebarboni** [comment]
would it be "legal" to do so?

**Comment by vieiro** [comment]
@ebarboni Well, if I write a tutorial myself and release it under the APLv2 then it's legal. I'm not going to copy the old tutorial, of course, I'm writing it new (in fact the old tutorial is quite oudated: id doesn't use annotations, for instance).

**Comment by mbien** [comment]
btw @vieiro NB has a sample repo now, in case your tutorial will need source code: https://github.com/apache/netbeans-samples

**Comment by vieiro** [comment]
> btw @vieiro NB has a sample repo now, in case your tutorial will need source code: https://github.com/apache/netbeans-samples

Yep, I know, @mbien . Thanks for the tip. If things go well (this is a big refactoring) then maybe it ends up in the main repo.

**Pull request merged**
